### PR TITLE
logging fix and removing overly complex if/then code

### PR DESCRIPTION
**Pull request by Flohack74**

### CODE REVIEW

**Comment by slp** [comment]
Honestly, I totally forgot about this project. Thanks for the PR!

**Comment by Flohack74** [comment]
Well we at UBports are currently ramping up our services for Matrix, and it came in quite handy that you did already have some code in Go. I was eager and forked it and reshaped it a bit for our needs: https://github.com/Flohack74/matrix-pushgw/tree/ubuntu-push-module - Thanks for the work! If you are looking for some coding fun with our mobile Linux OS, you are more than welcome :)

**Comment by slp** [comment]
Actually, for the last 2 weeks, I've been playing with UBports (and postmarketOS) on a Nexus 5. I was interested in helping to update Mir packages and libraries to play nice with halium's libhybris, and asked in the Telegram group (no mailing lists???) about how development was organized and coordinated , but had no answer :-(

**Comment by Flohack74** [comment]
Oh what a pity. We got mailing lists, but nobody is using them. Seems to be a first world problem xD. I can invite you to the Developers group if you like.

**Comment by Flohack74** [comment]
Contact me at florian at ubports.com

**Comment by slp** [comment]
@Flohack74 Sure, will do

**Comment by testbird** [comment]
Yeah, it's pity that spam degraded email and mailinglists. Fortunately, the autocrypt levels, and especially the https://github.com/deltachat/deltachat-core library comes to fixes the email flaws. It provides a nice email messaging api for applications.

**Pull request merged**
